spring:
  application:
    name: StartupInvestor

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/startupinvestor?characterEncoding=UTF-8&serverTimezone=UTC #내 로컬 mysql
    username: root
    password: 7663200

  jpa:
    #    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        hibernate:
          "[format_sql]": true            #SQL 보기 좋게 출력
          "[user_sql_comments]": true     #SQL 생성시 주석 포함
          "[highlight_sql]": true         #SQL 색깔
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false