spring:
  application:
    name: StartupInvestor

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/startupinvestor?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 7663200

  jpa:
    properties:
      hibernate:
        format_sql: true               # SQL 보기 좋게 출력
        use_sql_comments: true         # SQL 생성 시 주석 포함
        highlight_sql: true            # SQL 색상 강조
        transaction: org.hibernate.service.jta.platform.internal.NoJtaPlatform
    show-sql: true                      # SQL 출력
    hibernate:
      ddl-auto: create-drop                  # ddl-auto 설정
    open-in-view: false                 # Open session in view 패턴 사용 안 함
